[mypy]
ignore_missing_imports = True
explicit_package_bases = True

# SQLAlchemy Column descriptor type inference is imprecise
[mypy-api.v1.endpoints.*]
ignore_errors = True



[mypy-api.v2.endpoints.*]
ignore_errors = True

[mypy-workers.*]
ignore_errors = True

[mypy-core.auth]
ignore_errors = True

[mypy-ai.models.pytorch_runner]
ignore_errors = True

[mypy-ai.classification.classifier]
ignore_errors = True

[mypy-ai.classification.clip_classifier]
ignore_errors = True

[mypy-ai.recommendations.train_rl]
ignore_errors = True
