DEMO_VEHICLES = [
    {
        "name": "Bajaj RE (2019) — Standard Retrofit",
        "vehicle_type": "three_wheeler",
        "description": "Typical 2019 Bajaj RE with under-cargo battery placement. Minor frame asymmetry detected, otherwise good structural condition.",
        "assessment": {
            "assessment_state": "conditional",
            "confidence_score": 82,
            "confidence_factors": {
                "quality": 0.78,
                "geometry": 0.75,
                "visibility": 0.85,
                "completeness": 1.0,
                "classification": 0.88,
                "deviation_certainty": 0.70,
            },
            "safety_overrides": [],
            "feasibility_score": 78,
            "feasibility_label": "feasible_with_adaptation",
            "vehicle_classification": {
                "type": "three_wheeler",
                "confidence": 0.88,
                "human_confirmed": False,
                "classifier": "ONNX Vehicle Classifier v1",
                "model_loaded": True,
                "alternatives": [],
            },
            "deviation_summary": {
                "anomalies_detected": 2,
                "severity": "medium",
                "top_issues": [
                    "Frame asymmetry detected in left rail (12mm deviation)",
                    "Rear crossmember corrosion — structural assessment required",
                ],
            },
            "risk_summary": {
                "system_risk_state": "elevated",
                "critical_count": 0,
                "high_count": 1,
                "medium_count": 2,
                "low_count": 3,
            },
            "needs_confirmation": False,
            "compliance_state": "pass",
            "degradations": [
                {"service": "battery_optimizer", "message": "Battery zone optimizer using estimated geometry for underbody clearance", "fallback": "estimated_clearance"},
            ],
        },
        "recommendations": [
            {
                "title": "Under-Seat Battery Pack — 48V 100Ah LFP",
                "priority": "essential",
                "category": "battery_placement",
                "description": "Mount 48V LFP battery pack under the cargo bed with 15mm left offset to compensate for frame asymmetry.",
                "rationale": [
                    "Frame asymmetry (12mm left rail) requires offset compensation",
                    "Standard placement would cause battery-to-frame contact under load",
                    "Offset maintains 25mm minimum clearance on both sides",
                ],
                "blocking": True,
                "cost_estimate": {"min": 45000, "max": 55000, "currency": "INR"},
                "estimated_days": 2,
                "depends_on": ["frame_reinforcement"],
            },
            {
                "title": "Frame Rail Reinforcement — Left Side",
                "priority": "recommended",
                "category": "structural",
                "description": "Reinforce left frame rail at the asymmetry point with a 3mm steel gusset plate.",
                "rationale": [
                    "Frame asymmetry detected in left rail (moderate severity)",
                    "Reinforcement ensures structural integrity under EV payload",
                ],
                "blocking": False,
                "cost_estimate": {"min": 3500, "max": 6000, "currency": "INR"},
                "estimated_days": 0.5,
                "depends_on": [],
            },
            {
                "title": "Motor Mount — Mid-Drive 4kW BLDC",
                "priority": "essential",
                "category": "powertrain",
                "description": "Install 4kW BLDC mid-drive motor with chain drive to differential.",
                "rationale": [
                    "ICE engine removal frees transmission tunnel",
                    "Mid-drive configuration maintains rear axle weight distribution",
                    "4kW sufficient for urban auto-rickshaw duty cycle",
                ],
                "blocking": True,
                "cost_estimate": {"min": 25000, "max": 32000, "currency": "INR"},
                "estimated_days": 1.5,
                "depends_on": [],
            },
            {
                "title": "Wiring Harness — Chassis Rail Right Routing",
                "priority": "recommended",
                "category": "electrical",
                "description": "Route main HV harness along the right chassis rail, avoiding left-side corrosion zone.",
                "rationale": [
                    "Right rail provides clean, corrosion-free routing path",
                    "Avoids left-side structural repair zone",
                    "Keeps HV cable away from rear crossmember corrosion",
                ],
                "blocking": False,
                "cost_estimate": {"min": 4000, "max": 6500, "currency": "INR"},
                "estimated_days": 0.5,
                "depends_on": ["motor_mount"],
            },
        ],
        "risks": [
            {
                "severity": "high",
                "category": "structural",
                "message": "Frame asymmetry detected in left rail (12mm deviation)",
                "description": "Frame asymmetry requires structural reinforcement before battery mounting. Left rail shows 12mm outward bow at mid-section.",
                "confidence": 0.82,
            },
            {
                "severity": "medium",
                "category": "structural",
                "message": "Rear crossmember corrosion detected",
                "description": "Surface corrosion on rear crossmember may affect structural integrity. Recommend sanding and anti-corrosion treatment.",
                "confidence": 0.71,
            },
            {
                "severity": "medium",
                "category": "image_quality",
                "message": "Left side profile has moderate glare — geometric measurements confidence reduced",
                "description": "Partial occlusion from direct sunlight on left profile image.",
                "confidence": 0.65,
            },
            {
                "severity": "low",
                "category": "missing_view",
                "message": "Underbody view not submitted — battery placement optimization is preliminary",
                "description": "Underbody images would improve battery placement confidence by ~15%.",
                "confidence": 0.90,
            },
        ],
        "deviations": [
            {
                "component": "frame_left_rail",
                "severity": "medium",
                "description": "12mm outward bow detected in left frame rail at mid-section. Likely from prior overloading or collision damage.",
                "measurements": {"deviation_mm": 12, "location_mm_from_front": 1450},
            },
            {
                "component": "rear_crossmember",
                "severity": "medium",
                "description": "Surface corrosion on rear crossmember spanning approximately 200mm. Depth estimated at 1-2mm.",
                "measurements": {"corrosion_length_mm": 200, "estimated_depth_mm": 1.5},
            },
        ],
        "digital_twin": {
            "vehicle_type": "three_wheeler",
            "dimensions": {"length": 3100, "width": 1400, "height": 1750},
            "deviations_3d": [
                {
                    "parameter": "frame_left_rail_bow",
                    "location": "chassis_width",
                    "severity": "medium",
                    "delta_pct": 3.2,
                    "color": "#f59e0b",
                },
                {
                    "parameter": "rear_crossmember_corrosion",
                    "location": "underbody",
                    "severity": "medium",
                    "delta_pct": 0.8,
                    "color": "#f97316",
                },
            ],
            "retrofit_components": [
                {
                    "id": "battery_pack",
                    "label": "48V 100Ah LFP Battery",
                    "position": {"x": 0, "y": -0.15, "z": -0.45},
                    "color": "#22c55e",
                    "size": {"w": 0.6, "h": 0.18, "d": 0.7},
                },
                {
                    "id": "motor",
                    "label": "4kW BLDC Mid-Drive",
                    "position": {"x": 0.3, "y": -0.1, "z": 0.25},
                    "color": "#3b82f6",
                    "size": {"w": 0.25, "h": 0.2, "d": 0.25},
                },
                {
                    "id": "controller",
                    "label": "Motor Controller",
                    "position": {"x": 0.25, "y": 0.05, "z": 0.15},
                    "color": "#8b5cf6",
                    "size": {"w": 0.15, "h": 0.08, "d": 0.15},
                },
            ],
            "view_angles": {
                "default_camera": {"theta": 0.5, "phi": 0.6, "radius": 4.5},
            },
        },
        "estimated_total_cost_inr": 77500,
        "tooling_required": [
            "Welding equipment (MIG/TIG)",
            "Basic mechanic tools",
            "Multimeter and HV safety kit",
        ],
        "skill_level_required": "intermediate",
        "estimated_days": 5,
    },
    {
        "name": "Bajaj RE (2017) — Heavily Modified",
        "vehicle_type": "three_wheeler",
        "description": "2017 Bajaj RE with significant structural modifications: engine swap, extended cargo bed, non-standard suspension mounts. Represents the most challenging real-world retrofit case.",
        "assessment": {
            "assessment_state": "conditional",
            "confidence_score": 68,
            "confidence_factors": {
                "quality": 0.62,
                "geometry": 0.55,
                "visibility": 0.70,
                "completeness": 0.80,
                "classification": 0.72,
                "deviation_certainty": 0.60,
            },
            "safety_overrides": [
                "Safety override: classification < 40 AND geometry < 40 AND weak views",
            ],
            "feasibility_score": 58,
            "feasibility_label": "feasible_with_adaptation",
            "vehicle_classification": {
                "type": "three_wheeler",
                "confidence": 0.72,
                "human_confirmed": True,
                "classifier": "ONNX Vehicle Classifier v1",
                "model_loaded": True,
                "alternatives": [
                    {"vehicle_type": "motorcycle", "confidence": 0.21},
                ],
            },
            "deviation_summary": {
                "anomalies_detected": 5,
                "severity": "high",
                "top_issues": [
                    "Cargo bed extended by 450mm — non-standard rear overhang",
                    "Engine bay modified with non-OEM mounts (unstructured)",
                    "Suspension geometry altered — aftermarket units installed",
                    "Frame shows evidence of prior welding at 3 locations",
                    "Wheelbase asymmetry: left side 15mm longer than right",
                ],
            },
            "risk_summary": {
                "system_risk_state": "elevated",
                "critical_count": 1,
                "high_count": 3,
                "medium_count": 3,
                "low_count": 2,
            },
            "needs_confirmation": False,
            "compliance_state": "pass_with_caveats",
            "degradations": [
                {"service": "cv_model", "message": "OpenCV model running in degraded mode due to non-standard vehicle proportions", "fallback": "heuristic_classifier"},
                {"service": "geometry_engine", "message": "Reference geometry data partially unavailable for modified frame", "fallback": "estimated_geometry"},
            ],
        },
        "recommendations": [
            {
                "title": "Extended Cargo Bed Battery Pack — Custom 48V 120Ah LFP",
                "priority": "essential",
                "category": "battery_placement",
                "description": "Utilize extended cargo bed volume for a larger battery pack. Custom enclosure required to fit modified rear section.",
                "rationale": [
                    "Extended bed (450mm) provides additional under-floor volume",
                    "Standard under-seat position compromised by non-OEM engine mounts",
                    "Rear placement improves weight distribution given extended overhang",
                ],
                "blocking": True,
                "cost_estimate": {"min": 65000, "max": 85000, "currency": "INR"},
                "estimated_days": 3,
                "depends_on": ["suspension_rework", "frame_inspection"],
            },
            {
                "title": "Suspension Rework — Full Aftermarket Audit",
                "priority": "essential",
                "category": "structural",
                "description": "Full inspection and rework of aftermarket suspension units. Spring rates must be verified for EV payload.",
                "rationale": [
                    "Non-OEM suspension mounts have unknown load ratings",
                    "EV conversion adds 80-120kg battery weight",
                    "Aftermarket units may not be rated for increased payload",
                ],
                "blocking": True,
                "cost_estimate": {"min": 15000, "max": 25000, "currency": "INR"},
                "estimated_days": 2,
                "depends_on": [],
            },
            {
                "title": "Frame Weld Inspection & Reinforcement",
                "priority": "essential",
                "category": "structural",
                "description": "Inspect 3 prior weld locations with dye penetrant testing. Reinforce weak welds with proper MIG welds using appropriate filler.",
                "rationale": [
                    "3 prior weld locations detected on frame",
                    "Weld quality and filler material unknown",
                    "Structural integrity must be verified before EV conversion",
                ],
                "blocking": True,
                "cost_estimate": {"min": 8000, "max": 12000, "currency": "INR"},
                "estimated_days": 1,
                "depends_on": [],
            },
            {
                "title": "Mid-Drive Motor with Custom Mount",
                "priority": "recommended",
                "category": "powertrain",
                "description": "Install 5kW BLDC mid-drive motor with custom mounting bracket to accommodate modified engine bay.",
                "rationale": [
                    "Standard motor mount positions blocked by non-OEM engine mounts",
                    "Custom bracket required to adapt to existing mounting points",
                    "5kW rating recommended to compensate for increased vehicle weight",
                ],
                "blocking": False,
                "cost_estimate": {"min": 30000, "max": 38000, "currency": "INR"},
                "estimated_days": 2,
                "depends_on": ["suspension_rework"],
            },
        ],
        "risks": [
            {
                "severity": "critical",
                "category": "structural",
                "message": "Frame history of 3 undocumented welds — structural integrity unverified",
                "description": "Prior welding detected at 3 points on main frame. Weld quality and material compatibility unknown. Critical safety concern for EV conversion.",
                "confidence": 0.88,
            },
            {
                "severity": "high",
                "category": "structural",
                "message": "Suspension mounts are non-OEM and of unknown rating",
                "description": "Aftermarket suspension units fitted with non-standard brackets. Load ratings not available. Likely insufficient for EV conversion weight.",
                "confidence": 0.85,
            },
            {
                "severity": "high",
                "category": "structural",
                "message": "Wheelbase asymmetry: left side 15mm longer than right",
                "description": "Wheelbase mismatch indicates possible frame twist or accident damage. Requires alignment check before proceeding.",
                "confidence": 0.78,
            },
            {
                "severity": "high",
                "category": "modification",
                "message": "Cargo bed extended 450mm — non-standard rear overhang affects weight distribution",
                "description": "Extended cargo bed shifts rear axle loading. Battery placement optimization needed to maintain axle load limits.",
                "confidence": 0.90,
            },
            {
                "severity": "medium",
                "category": "image_quality",
                "message": "Engine bay view has poor lighting — mount assessment is preliminary",
                "description": "Dark engine bay images limit confidence in mount type identification.",
                "confidence": 0.55,
            },
            {
                "severity": "medium",
                "category": "missing_view",
                "message": "Underbody view not submitted — critical for weld inspection validation",
                "description": "Underbody images would help verify weld locations and frame condition.",
                "confidence": 0.90,
            },
        ],
        "deviations": [
            {
                "component": "frame_welds",
                "severity": "critical",
                "description": "Three undocumented weld locations detected on main frame rails. Quality and filler material unknown — structural integrity concern.",
                "measurements": {"weld_count": 3, "location_front_mm": 800, "location_mid_mm": 1600, "location_rear_mm": 2400},
            },
            {
                "component": "cargo_bed",
                "severity": "high",
                "description": "Cargo bed extended by 450mm beyond OEM specification. Non-standard rear overhang affects dynamic stability.",
                "measurements": {"extension_mm": 450, "total_bed_length_mm": 1850},
            },
            {
                "component": "suspension_mounts",
                "severity": "high",
                "description": "Non-OEM aftermarket suspension units installed. Unknown load rating and manufacturer.",
                "measurements": {"mount_type": "non_standard", "manufacturer_identified": False},
            },
            {
                "component": "wheelbase",
                "severity": "high",
                "description": "Wheelbase asymmetry: left side measures 15mm longer than right side. Possible frame twist or accident damage.",
                "measurements": {"left_mm": 2680, "right_mm": 2665, "difference_mm": 15},
            },
            {
                "component": "engine_bay",
                "severity": "medium",
                "description": "Engine bay modified with non-OEM mounts. Original mounting structure removed or altered.",
                "measurements": {"mount_type": "non_standard", "original_mounts_removed": True},
            },
        ],
        "digital_twin": {
            "vehicle_type": "three_wheeler",
            "dimensions": {"length": 3550, "width": 1400, "height": 1780},
            "deviations_3d": [
                {
                    "parameter": "cargo_bed_extension",
                    "location": "cargo_area",
                    "severity": "high",
                    "delta_pct": 14.5,
                    "color": "#ef4444",
                },
                {
                    "parameter": "frame_weld_locations",
                    "location": "chassis_width",
                    "severity": "critical",
                    "delta_pct": 5.0,
                    "color": "#dc2626",
                },
                {
                    "parameter": "wheelbase_asymmetry",
                    "location": "chassis_width",
                    "severity": "high",
                    "delta_pct": 0.6,
                    "color": "#f59e0b",
                },
                {
                    "parameter": "suspension_modification",
                    "location": "underbody",
                    "severity": "high",
                    "delta_pct": 8.0,
                    "color": "#f97316",
                },
                {
                    "parameter": "engine_bay_modification",
                    "location": "underbody",
                    "severity": "medium",
                    "delta_pct": 12.0,
                    "color": "#eab308",
                },
            ],
            "retrofit_components": [
                {
                    "id": "battery_pack",
                    "label": "48V 120Ah LFP Battery (Extended)",
                    "position": {"x": 0, "y": -0.2, "z": -0.6},
                    "color": "#22c55e",
                    "size": {"w": 0.7, "h": 0.2, "d": 0.8},
                },
                {
                    "id": "motor",
                    "label": "5kW BLDC Mid-Drive",
                    "position": {"x": 0.25, "y": -0.15, "z": 0.3},
                    "color": "#3b82f6",
                    "size": {"w": 0.3, "h": 0.22, "d": 0.3},
                },
                {
                    "id": "controller",
                    "label": "Motor Controller",
                    "position": {"x": 0.2, "y": 0.0, "z": 0.2},
                    "color": "#8b5cf6",
                    "size": {"w": 0.18, "h": 0.08, "d": 0.18},
                },
            ],
            "view_angles": {
                "default_camera": {"theta": 0.5, "phi": 0.6, "radius": 5.0},
            },
        },
        "estimated_total_cost_inr": 118000,
        "tooling_required": [
            "Welding equipment (MIG/TIG) with filler material for frame",
            "Dye penetrant testing kit for weld inspection",
            "Full mechanic toolset",
            "HV safety kit and insulation tester",
            "Suspension spring compressor",
        ],
        "skill_level_required": "advanced",
        "estimated_days": 10,
    },
    {
        "name": "Piaggio Ape (2021) — Clean Retrofit Candidate",
        "vehicle_type": "three_wheeler",
        "description": "2021 Piaggio Ape in good structural condition. Minimal deviations, excellent photo quality. Prime candidate for standard EV conversion.",
        "assessment": {
            "assessment_state": "full_confidence",
            "confidence_score": 91,
            "confidence_factors": {
                "quality": 0.92,
                "geometry": 0.88,
                "visibility": 0.90,
                "completeness": 1.0,
                "classification": 0.94,
                "deviation_certainty": 0.85,
            },
            "safety_overrides": [],
            "feasibility_score": 88,
            "feasibility_label": "feasible",
            "vehicle_classification": {
                "type": "three_wheeler",
                "confidence": 0.94,
                "human_confirmed": False,
                "classifier": "ONNX Vehicle Classifier v1",
                "model_loaded": True,
                "alternatives": [],
            },
            "deviation_summary": {
                "anomalies_detected": 0,
                "severity": "low",
                "top_issues": [],
            },
            "risk_summary": {
                "system_risk_state": "nominal",
                "critical_count": 0,
                "high_count": 0,
                "medium_count": 0,
                "low_count": 1,
            },
            "needs_confirmation": False,
            "compliance_state": "pass",
            "degradations": [],
        },
        "recommendations": [
            {
                "title": "Under-Seat Battery Pack — 48V 80Ah LFP",
                "priority": "essential",
                "category": "battery_placement",
                "description": "Mount 48V LFP battery pack in the standard under-seat position. No deviation compensation required.",
                "rationale": [
                    "Vehicle in good structural condition — standard placement viable",
                    "80Ah capacity sufficient for typical urban daily range (~80km)",
                    "Under-seat position maintains OEM weight distribution",
                ],
                "blocking": True,
                "cost_estimate": {"min": 38000, "max": 45000, "currency": "INR"},
                "estimated_days": 1.5,
                "depends_on": [],
            },
            {
                "title": "Motor Mount — Standard 4kW BLDC",
                "priority": "essential",
                "category": "powertrain",
                "description": "Install 4kW BLDC motor using OEM engine mounting points. No custom fabrication required.",
                "rationale": [
                    "Clean engine bay with OEM mounting points intact",
                    "Standard 4kW sufficient for Piaggio Ape duty cycle",
                    "No structural modifications required",
                ],
                "blocking": True,
                "cost_estimate": {"min": 22000, "max": 28000, "currency": "INR"},
                "estimated_days": 1,
                "depends_on": [],
            },
            {
                "title": "Wiring Harness — Standard Routing",
                "priority": "recommended",
                "category": "electrical",
                "description": "Route HV harness along right chassis rail following OEM cable routing paths.",
                "rationale": [
                    "No corrosion or structural issues affecting routing",
                    "OEM routing paths available and intact",
                    "Standard installation procedures apply",
                ],
                "blocking": False,
                "cost_estimate": {"min": 3500, "max": 5000, "currency": "INR"},
                "estimated_days": 0.5,
                "depends_on": ["motor_mount"],
            },
        ],
        "risks": [
            {
                "severity": "low",
                "category": "image_quality",
                "message": "Minor lens flare on right side profile — no material impact on measurements",
                "description": "Slight glare on one image, but all structural measurements confirmed with high confidence.",
                "confidence": 0.80,
            },
        ],
        "deviations": [],
        "digital_twin": {
            "vehicle_type": "three_wheeler",
            "dimensions": {"length": 3200, "width": 1450, "height": 1800},
            "deviations_3d": [],
            "retrofit_components": [
                {
                    "id": "battery_pack",
                    "label": "48V 80Ah LFP Battery",
                    "position": {"x": 0, "y": -0.1, "z": -0.4},
                    "color": "#22c55e",
                    "size": {"w": 0.5, "h": 0.16, "d": 0.6},
                },
                {
                    "id": "motor",
                    "label": "4kW BLDC Standard Mount",
                    "position": {"x": 0.35, "y": -0.08, "z": 0.25},
                    "color": "#3b82f6",
                    "size": {"w": 0.22, "h": 0.18, "d": 0.22},
                },
                {
                    "id": "controller",
                    "label": "Motor Controller",
                    "position": {"x": 0.3, "y": 0.06, "z": 0.15},
                    "color": "#8b5cf6",
                    "size": {"w": 0.14, "h": 0.06, "d": 0.14},
                },
            ],
            "view_angles": {
                "default_camera": {"theta": 0.5, "phi": 0.6, "radius": 4.5},
            },
        },
        "estimated_total_cost_inr": 63500,
        "tooling_required": [
            "Basic mechanic tools",
            "Multimeter and HV safety kit",
        ],
        "skill_level_required": "beginner",
        "estimated_days": 3,
    },
    {
        "name": "Maruti Suzuki Alto (2018) — Four Wheeler EV Conversion",
        "vehicle_type": "four_wheeler",
        "description": "2018 Maruti Suzuki Alto in good structural condition. Minor front-end panel misalignment from a prior fender bender. Ideal four-wheeler retrofit candidate for urban delivery fleets.",
        "assessment": {
            "assessment_state": "full_confidence",
            "confidence_score": 85,
            "confidence_factors": {
                "quality": 0.82,
                "geometry": 0.78,
                "visibility": 0.85,
                "completeness": 1.0,
                "classification": 0.90,
                "deviation_certainty": 0.75,
            },
            "safety_overrides": [],
            "feasibility_score": 80,
            "feasibility_label": "feasible_with_adaptation",
            "vehicle_classification": {
                "type": "four_wheeler",
                "confidence": 0.90,
                "human_confirmed": False,
                "classifier": "Heuristic",
                "model_loaded": False,
                "alternatives": [],
            },
            "deviation_summary": {
                "anomalies_detected": 1,
                "severity": "low",
                "top_issues": [
                    "Front bumper cover misaligned by 8mm on driver side — cosmetic only",
                ],
            },
            "risk_summary": {
                "system_risk_state": "normal",
                "critical_count": 0,
                "high_count": 0,
                "medium_count": 1,
                "low_count": 1,
            },
            "needs_confirmation": False,
            "compliance_state": "pass",
            "degradations": [],
        },
        "recommendations": [
            {
                "title": "Under-Floor Battery Pack — 72V 80Ah LFP",
                "priority": "essential",
                "category": "battery_placement",
                "description": "Mount 72V LFP battery pack in the OEM spare wheel well and under rear seat area. Custom enclosure required to fit Alto floor pan.",
                "rationale": [
                    "72V architecture compatible with 5-7kW mid-drive motors",
                    "80Ah provides ~100km urban range for delivery use",
                    "Under-floor placement maintains cabin space and weight distribution",
                ],
                "blocking": True,
                "cost_estimate": {"min": 55000, "max": 70000, "currency": "INR"},
                "estimated_days": 2.5,
                "depends_on": [],
            },
            {
                "title": "Mid-Drive Motor — 5kW BLDC with Reduction Gear",
                "priority": "essential",
                "category": "powertrain",
                "description": "Install 5kW BLDC mid-drive motor coupled to OEM transmission via adapter plate. Reduction gear maintains torque at low speeds.",
                "rationale": [
                    "5kW sufficient for Alto kerb weight (~700kg) plus payload",
                    "Mid-drive preserves OEM gear ratios for hill climbing",
                    "Adapter plate avoids permanent transmission modification",
                ],
                "blocking": True,
                "cost_estimate": {"min": 32000, "max": 40000, "currency": "INR"},
                "estimated_days": 2,
                "depends_on": [],
            },
            {
                "title": "72V 250A Motor Controller with Regenerative Braking",
                "priority": "essential",
                "category": "electrical",
                "description": "Install 72V 250A sine-wave motor controller with regen braking support. Configure regen strength for urban stop-and-go driving.",
                "rationale": [
                    "250A capacity handles 5kW motor peak current (72V * 250A = 18kW peak)",
                    "Regenerative braking recovers 10-15% energy in city driving",
                    "Sine-wave drive provides quiet operation vs trapezoidal controllers",
                ],
                "blocking": True,
                "cost_estimate": {"min": 18000, "max": 25000, "currency": "INR"},
                "estimated_days": 1,
                "depends_on": ["battery_pack", "motor_installation"],
            },
            {
                "title": "HV Wiring Harness — Chassis Rail Routing",
                "priority": "recommended",
                "category": "electrical",
                "description": "Route 72V HV cabling along driver-side chassis rail with grommets at all pass-through points. Install manual service disconnect at battery outlet.",
                "rationale": [
                    "Driver-side rail provides shortest path from rear battery to front controller",
                    "Grommets prevent chafing at sheet metal pass-throughs",
                    "Manual service disconnect required for safe maintenance",
                ],
                "blocking": False,
                "cost_estimate": {"min": 6000, "max": 9000, "currency": "INR"},
                "estimated_days": 0.5,
                "depends_on": ["controller_and_bms"],
            },
        ],
        "risks": [
            {
                "severity": "medium",
                "category": "structural",
                "message": "Front bumper cover misaligned 8mm — prior fender bender may indicate sub-frame tweak",
                "description": "8mm misalignment at driver-side bumper mount point. Sub-frame alignment should be verified before motor mount installation.",
                "confidence": 0.65,
            },
            {
                "severity": "low",
                "category": "modification",
                "message": "Under-floor battery enclosure requires custom fabrication — no OEM bracket available",
                "description": "Spare wheel well must be modified to accept battery enclosure. CAD model should be generated for fabrication.",
                "confidence": 0.80,
            },
        ],
        "deviations": [
            {
                "component": "front_bumper_cover",
                "severity": "low",
                "description": "Front bumper cover misaligned by 8mm on driver side. Likely from prior low-speed collision. Cosmetic only — no structural impact.",
                "measurements": {"misalignment_mm": 8, "location": "driver_side_mount"},
            },
        ],
        "digital_twin": {
            "vehicle_type": "four_wheeler",
            "dimensions": {"length": 4000, "width": 1600, "height": 1500},
            "deviations_3d": [
                {
                    "parameter": "front_bumper_misalignment",
                    "location": "front",
                    "severity": "low",
                    "delta_pct": 0.5,
                    "color": "#eab308",
                },
            ],
            "retrofit_components": [
                {
                    "id": "battery_pack",
                    "label": "72V 80Ah LFP Battery",
                    "position": {"x": 0, "y": -0.25, "z": -0.6},
                    "color": "#22c55e",
                    "size": {"w": 0.8, "h": 0.2, "d": 1.0},
                },
                {
                    "id": "motor",
                    "label": "5kW BLDC Mid-Drive",
                    "position": {"x": 0.5, "y": -0.15, "z": 0.45},
                    "color": "#3b82f6",
                    "size": {"w": 0.3, "h": 0.25, "d": 0.3},
                },
                {
                    "id": "controller",
                    "label": "72V 250A Controller",
                    "position": {"x": 0.45, "y": 0.08, "z": 0.25},
                    "color": "#8b5cf6",
                    "size": {"w": 0.2, "h": 0.1, "d": 0.2},
                },
            ],
            "view_angles": {
                "default_camera": {"theta": 0.5, "phi": 0.6, "radius": 6.0},
            },
        },
        "estimated_total_cost_inr": 111000,
        "tooling_required": [
            "Welding equipment for battery enclosure fabrication",
            "Mechanic toolset with torque wrench",
            "HV safety kit (gloves, mat, lockout/tagout)",
            "Multimeter and insulation tester",
        ],
        "skill_level_required": "intermediate",
        "estimated_days": 6,
    },
    {
        "name": "Hero Splendor (2020) — Motorcycle EV Conversion",
        "vehicle_type": "motorcycle",
        "description": "2020 Hero Splendor in excellent condition with minimal mileage. Body is clean, frame is straight, and all electrical systems functional. Ideal first motorcycle EV conversion project.",
        "assessment": {
            "assessment_state": "full_confidence",
            "confidence_score": 92,
            "confidence_factors": {
                "quality": 0.90,
                "geometry": 0.88,
                "visibility": 0.92,
                "completeness": 1.0,
                "classification": 0.95,
                "deviation_certainty": 0.85,
            },
            "safety_overrides": [],
            "feasibility_score": 90,
            "feasibility_label": "feasible",
            "vehicle_classification": {
                "type": "motorcycle",
                "confidence": 0.95,
                "human_confirmed": False,
                "classifier": "Heuristic",
                "model_loaded": False,
                "alternatives": [],
            },
            "deviation_summary": {
                "anomalies_detected": 0,
                "severity": "low",
                "top_issues": [],
            },
            "risk_summary": {
                "system_risk_state": "normal",
                "critical_count": 0,
                "high_count": 0,
                "medium_count": 0,
                "low_count": 1,
            },
            "needs_confirmation": False,
            "compliance_state": "pass",
            "degradations": [
                {"service": "wiring_router", "message": "Wiring guidance limited for motorcycle frame — standard routing templates do not cover 2-wheeler layouts", "fallback": "generic_routing"},
            ],
        },
        "recommendations": [
            {
                "title": "Battery Pack — 48V 40Ah LFP (Under-Seat)",
                "priority": "essential",
                "category": "battery_placement",
                "description": "Mount 48V LFP battery pack under the seat in place of the removed fuel tank. Slim profile fits within frame rails.",
                "rationale": [
                    "48V architecture is standard for motorcycle EV conversions",
                    "40Ah provides ~70km urban range for daily commuting",
                    "Under-seat placement lowers center of gravity vs tank location",
                ],
                "blocking": True,
                "cost_estimate": {"min": 28000, "max": 35000, "currency": "INR"},
                "estimated_days": 1.5,
                "depends_on": [],
            },
            {
                "title": "Hub Motor — 2kW BLDC Rear Wheel",
                "priority": "essential",
                "category": "powertrain",
                "description": "Replace rear wheel with 2kW BLDC hub motor. Direct-drive eliminates chain and sprocket complexity.",
                "rationale": [
                    "2kW sufficient for 110cc motorcycle class (top speed ~60km/h)",
                    "Hub motor preserves clean aesthetic — no visible motor assembly",
                    "Eliminates chain maintenance and reduces drivetrain loss",
                ],
                "blocking": True,
                "cost_estimate": {"min": 15000, "max": 20000, "currency": "INR"},
                "estimated_days": 1,
                "depends_on": [],
            },
            {
                "title": "48V 30A Sine-Wave Controller",
                "priority": "essential",
                "category": "electrical",
                "description": "Install 48V 30A sine-wave controller with regen braking. Compact size fits under seat alongside battery.",
                "rationale": [
                    "30A x 48V = 1440W continuous, matching 2kW peak motor rating",
                    "Sine-wave drive provides smooth throttle response",
                    "Regen braking recovers energy and reduces brake pad wear",
                ],
                "blocking": True,
                "cost_estimate": {"min": 8000, "max": 12000, "currency": "INR"},
                "estimated_days": 0.5,
                "depends_on": ["battery_pack", "motor_selection"],
            },
            {
                "title": "12V DC-DC Converter for Auxiliary Systems",
                "priority": "recommended",
                "category": "electrical",
                "description": "Install 48V-to-12V DC-DC converter to power existing lights, horn, and indicators. Use OEM switchgear for stock appearance.",
                "rationale": [
                    "Motorcycle auxiliary systems run on 12V — converter required",
                    "OEM switchgear retains stock look and feel",
                    "10A output sufficient for LED lights and basic accessories",
                ],
                "blocking": False,
                "cost_estimate": {"min": 2500, "max": 4000, "currency": "INR"},
                "estimated_days": 0.5,
                "depends_on": ["controller_and_bms"],
            },
        ],
        "risks": [
            {
                "severity": "low",
                "category": "modification",
                "message": "Under-seat battery enclosure must be custom fabricated to fit frame triangle",
                "description": "Battery shape must conform to the frame triangle. Aluminum enclosure recommended for weight savings.",
                "confidence": 0.75,
            },
        ],
        "deviations": [],
        "digital_twin": {
            "vehicle_type": "motorcycle",
            "dimensions": {"length": 2000, "width": 750, "height": 1100},
            "deviations_3d": [],
            "retrofit_components": [
                {
                    "id": "battery_pack",
                    "label": "48V 40Ah LFP Battery",
                    "position": {"x": 0, "y": 0.1, "z": -0.15},
                    "color": "#22c55e",
                    "size": {"w": 0.25, "h": 0.12, "d": 0.35},
                },
                {
                    "id": "motor",
                    "label": "2kW BLDC Hub Motor",
                    "position": {"x": 0, "y": -0.15, "z": 0.4},
                    "color": "#3b82f6",
                    "size": {"w": 0.15, "h": 0.15, "d": 0.12},
                },
                {
                    "id": "controller",
                    "label": "48V 30A Controller",
                    "position": {"x": 0, "y": 0.0, "z": 0.05},
                    "color": "#8b5cf6",
                    "size": {"w": 0.12, "h": 0.06, "d": 0.12},
                },
            ],
            "view_angles": {
                "default_camera": {"theta": 0.5, "phi": 0.6, "radius": 3.5},
            },
        },
        "estimated_total_cost_inr": 53500,
        "tooling_required": [
            "Basic mechanic tools",
            "Multimeter and HV safety kit",
            "Angle grinder for battery enclosure fabrication",
        ],
        "skill_level_required": "intermediate",
        "estimated_days": 4,
    },
]
